defmodule WarhammerCharacters.Character do
  alias WarhammerCharacters.Character

  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    api: WarhammerCharacters.Api

  code_interface do
    define_for WarhammerCharacters.Api
    define :create, action: :create
    define :read_all, action: :read
    define :update, action: :update
    define :destroy, action: :destroy
    define :get_by_id, args: [:id], action: :by_id
  end

  actions do
    # Add a set of simple actions. You'll customize these later.
    defaults [:read, :update, :destroy]

    create :create do
      primary? true

      argument :characteristics, :map
      argument :skills, {:array, :map}
      argument :talents, {:array, :map}

      change manage_relationship(:characteristics, :characteristics, type: :create)
      change manage_relationship(:skills, :skills, type: :create)
      change manage_relationship(:talents, :talents, type: :create)
    end

    read :by_id do
      # This action has one argument :id of type :uuid
      argument :id, :uuid, allow_nil?: false
      # Tells us we expect this action to return a single result
      get? true
      # Filters the `:id` given in the argument
      # against the `id` of each element in the resource
      filter expr(id == ^arg(:id))
    end
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :name, :string
    attribute :age, :string
    attribute :species, :string
    attribute :status, :string
    attribute :player, :string
    attribute :career, :string
    attribute :career_path, :string
  end

  relationships do
    has_one :characteristics, Character.Characteristics
    has_many :skills, Character.Skill
    has_many :talents, Character.Talent
  end

  postgres do
    table "characters"
    repo WarhammerCharacters.Repo
  end
end
