defmodule WarhammerCharacters.Repo.Migrations.AddCharacteristics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:characteristics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :weapon_skill, :bigint
      add :ballistic_skill, :bigint
      add :strength, :bigint
      add :toughness, :bigint
      add :initiative, :bigint
      add :agility, :bigint
      add :dextirity, :bigint
      add :integelligence, :bigint
      add :willpower, :bigint
      add :fellowship, :bigint

      add :character_id,
          references(:characters,
            column: :id,
            name: "characteristics_character_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:characteristics, "characteristics_character_id_fkey")

    drop table(:characteristics)
  end
end
